### ISSUE TITLE
Under what license do you publish your components?

### ISSUE THREAD

**Issue by Lockhead** [franky47/francoisbest.com#38]
I'm espacilly asking about francoisbest.com/blob/next/src/components/SHA256Avatar.tsx

**Comment by franky47** [comment]
Technically there is no license, I only license NPM-shipped code.

You can reuse this file with modifications, as long as you include an attribution link (to [the article](https://preview.francoisbest.com/posts/2021/hashvatars), it makes more sense as the component file location might move in the future).

**Comment by Lockhead** [comment]
I would love to do, but I'm sadly not allowed to use external code without a licence, any chance you could publish that code as NPM package?

**Comment by franky47** [comment]
What is your intended use-case ?

**Comment by Lockhead** [comment]
Essentially what github is doing for avatars, but I'm looking for something with a higher dimensionality. I looked into robohash and monsterid but their solutions is to specific and I was looking for a more generic look and feel and the classic approach by deterministically choosing a background color and extracting initials from a name has to many collisions. So I stumpled over your blog post that was pushed to hacker news in april and this fits well as the amount of colors creates a big enough space for my use case without creating combinations that could be "not liked" by the affected identities...

**Comment by franky47** [comment]
After many cryptobros tried to use this code for NFT projects, I've added a disclaimer in the article that it's not allowed to be used for such purposes, and for this reason I won't package it on NPM.
